routes/web.php
<?php

use App\Http\Controllers\InfoController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('infos', InfoController::class)->except('show');

app/Models/Info.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Info extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'link', 'tags', 'teaser', 'content'];

    public function arrayWithTags(Info $info){
        return explode(",", $info->tags);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/InfoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreInfoRequest;
use App\Http\Requests\UpdateInfoRequest;
use App\Models\Info;
use Illuminate\Http\Request;

class InfoController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $infos = Info::latest()->simplePaginate(15);

        return view('infos.index', ['infos' => $infos]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('infos.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreInfoRequest $request)
    {
        Info::create($request->validated());

        return redirect()->route('infos.index');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Info $info)
    {
        return view('infos.edit', ['info' => $info]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateInfoRequest $request, Info $info)
    {
        $info->update($request->validated());
        return redirect()->route('infos.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Info $info)
    {
        $info->delete();
        return redirect()->route('infos.index');
    }
}

app/View/Components/Input.php
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;
use App\Models\Info;

class Input extends Component
{
    /**
     * Create a new component instance.
     */

    public function __construct(
        public string $name,
        public string $input,
        public ?Info $model
    ){}

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.input');
    }
}

resources/views/infos/create.blade.php
<x-layout>
<h1 class="w-3/4 mx-auto text-center text-2xl font-bold">Create Info</h1>
<form method="POST" action="{{route('infos.store')}}" class="w-3/4 mx-auto py-4">
    @csrf

    <x-input input="text" name="title"></x-input>
    <x-input input="text" name="link"></x-input>
    <x-input input="text" name="tags"></x-input>
    <x-input input="textarea" name="teaser"></x-input>
    <x-input input="textarea" name="content"></x-input>

    <div class="flex justify-center gap-2">
        <input type="submit" value="Create"
            class="border-2 border-black px-2 py-1 rounded-lg hover:bg-black hover:text-white cursor-pointer">
        <a href="{{route('infos.index')}}"
            class="border-2 border-black px-2 py-1 rounded-lg hover:bg-black hover:text-white cursor-pointer">
            Back
        </a>
    </div>
</form>
</x-layout>

resources/views/infos/edit.blade.php
<x-layout>
    <h1 class="w-3/4 mx-auto text-center text-2xl font-bold">Edit Info</h1>
    <form method="POST" action="{{route('infos.update', [$info])}}" class="w-3/4 mx-auto py-4">
        @csrf
        @method('PUT')

        <x-input input="text" name="title" :model=$info></x-input>
        <x-input input="text" name="link" :model=$info></x-input>
        <x-input input="text" name="tags" :model=$info></x-input>
        <x-input input="textarea" name="teaser" :model=$info></x-input>
        <x-input input="textarea" name="content" :model=$info></x-input>

        <div class="flex justify-center gap-2">
            <input type="submit" value="Save"
                class="border-2 border-black px-2 py-1 rounded-lg hover:bg-black hover:text-white cursor-pointer">
            <a href="{{route('infos.index')}}"
                class="border-2 border-black px-2 py-1 rounded-lg hover:bg-black hover:text-white cursor-pointer">
                Back
            </a>
        </div>
    </form>
    </x-layout>

resources/views/infos/index.blade.php
<x-layout>
<div class="flex justify-center mb-4">
    {{ $infos->links() }}
</div>
@forelse ($infos as $info)
<div x-data="{ show_content: false }" class="mb-12 text-black">
    <div class="black border-black border-4 rounded-md relative flex items-center">
        <div class="text-center font-medium text-xl pt-2 pb-4 px-4 w-full">
            @if ($info->link)
                <a class="underline" href="{{$info->link}}">{{ $info->title}}</a>
            @else
                {{ $info->title}}
            @endif
        </div>
        <div class="absolute z-1 -bottom-3 flex justify-center w-full text-sm gap-2">
            @foreach ($info->arrayWithTags($info) as $tag)
            <span class="bg-white border-black border-2 black rounded-lg px-2">{{$tag}}</span>
            @endforeach
        </div>
        <div class="absolute justify-center w-full -bottom-3 flex gap-1">

        </div>
        <div class="absolute -top-4 right-2 flex gap-1">
            <button x-on:click="show_content = ! show_content"
                class="border-4 border-black rounded-full bg-white w-8 text-sm font-medium
                hover:bg-black hover:text-white cursor-pointer">
                   T
            </button>
            <a href="{{route('infos.edit', ['info' => $info])}}"
                class="border-4 border-black rounded-full bg-white w-8 text-sm font-medium text-center
                hover:bg-black hover:text-white cursor-pointer">E</a>
            <form method="POST" action="{{route('infos.destroy', ['info' => $info])}}">
                @csrf
                @method('DELETE')
                <input type="submit" value="D"
                    class=" border-4 border-black rounded-full bg-white w-8 text-sm font-medium
                        hover:bg-black hover:text-white cursor-pointer">
            </form>
        </div>
    </div>
    <div class="relative">
        <div class="px-4">
            <div class="black border-black border-x-4 border-b-4 rounded-b-md pt-1">
                <div class="flex ">
                    <div class=" px-5 py-2 w-full">
                        <div class="div mb-2">
                            {{ $info->teaser}}
                        </div>
                    </div>
                </div>
                <div x-show="show_content" class="px-5 pb-4 py-2 border-black border-t-2">
                    {{ $info->content}}
                </div>
            </div>
        </div>
    </div>
</div>
@empty
<div class="text-center text-2xl">
    Keine Infos vorhanden.
</div>
@endforelse
<div class="flex justify-center mb-4">
    {{ $infos->links() }}
</div>
</x-layout>